# Generated by Django 3.1.2 on 2020-10-23 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20201023_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('category', models.CharField(choices=[('r', 'residence'), ('w', 'workplace'), ('v', 'visit')], max_length=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.location')),
            ],
        ),
    ]
