# Generated by Django 3.1.2 on 2020-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='y',
            field=models.FloatField(),
        ),
    ]
